using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace UITK.CodeBehind.Editor
{
    public static class CodeBehindGenerator
    {
        public static string ViewsNamespace { get; set; } = "UI.Views";

        private static readonly string GeneratedPath = "Assets/Scripts/UI/Generated";
        private static readonly string ViewsPath = $"{GeneratedPath}/Views";

        public static void GenerateAll()
        {
            var views = UxmlScanner.ScanAllViews();
            if (views.Count == 0)
            {
                Debug.Log("CodeBehindGenerator: no views found in Resources/Views/");
                return;
            }

            if (Directory.Exists(GeneratedPath))
                Directory.Delete(GeneratedPath, true);
            Directory.CreateDirectory(ViewsPath);

            foreach (var view in views)
                WriteViewGenerated(view);

            AssetDatabase.Refresh();
            Debug.Log($"CodeBehindGenerator: generated {views.Count} view files");
        }

        private static void WriteViewGenerated(ScannedView view)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using UITK.CodeBehind;");
            sb.AppendLine("using UnityEngine.UIElements;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ViewsNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {view.ClassName}");
            sb.AppendLine("    {");

            foreach (var el in view.Elements)
                sb.AppendLine($"        private {GetTypeName(el.ElementType)} {UxmlScanner.ToPascalCase(el.Name)};");

            sb.AppendLine();
            sb.AppendLine("        protected override void OnActivate()");
            sb.AppendLine("        {");
            foreach (var el in view.Elements)
            {
                var query = el.ElementType == typeof(Button)
                    ? $"Root.B(\"{el.Name}\")"
                    : el.ElementType == typeof(Slider)
                        ? $"Root.S(\"{el.Name}\")"
                        : el.ElementType == typeof(Label)
                            ? $"Root.L(\"{el.Name}\")"
                            : el.ElementType == typeof(Image)
                                ? $"Root.I(\"{el.Name}\")"
                                : $"Root.Q<{GetTypeName(el.ElementType)}>(\"{el.Name}\")";
                sb.AppendLine($"            {UxmlScanner.ToPascalCase(el.Name)} = {query};");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText($"{ViewsPath}/{view.ClassName}.g.cs", sb.ToString());
        }

        private static string GetTypeName(Type type)
        {
            if (type == typeof(Button)) return "Button";
            if (type == typeof(Label)) return "Label";
            if (type == typeof(Slider)) return "Slider";
            if (type == typeof(SliderInt)) return "SliderInt";
            if (type == typeof(MinMaxSlider)) return "MinMaxSlider";
            if (type == typeof(Image)) return "Image";
            if (type == typeof(ScrollView)) return "ScrollView";
            if (type == typeof(Toggle)) return "Toggle";
            if (type == typeof(ToggleButtonGroup)) return "ToggleButtonGroup";
            if (type == typeof(RadioButton)) return "RadioButton";
            if (type == typeof(RadioButtonGroup)) return "RadioButtonGroup";
            if (type == typeof(TextField)) return "TextField";
            if (type == typeof(IntegerField)) return "IntegerField";
            if (type == typeof(LongField)) return "LongField";
            if (type == typeof(FloatField)) return "FloatField";
            if (type == typeof(DoubleField)) return "DoubleField";
            if (type == typeof(Vector2Field)) return "Vector2Field";
            if (type == typeof(Vector3Field)) return "Vector3Field";
            if (type == typeof(Vector4Field)) return "Vector4Field";
            if (type == typeof(Vector2IntField)) return "Vector2IntField";
            if (type == typeof(Vector3IntField)) return "Vector3IntField";
            if (type == typeof(RectField)) return "RectField";
            if (type == typeof(RectIntField)) return "RectIntField";
            if (type == typeof(BoundsField)) return "BoundsField";
            if (type == typeof(BoundsIntField)) return "BoundsIntField";
            if (type == typeof(Hash128Field)) return "Hash128Field";
            if (type == typeof(UnsignedIntegerField)) return "UnsignedIntegerField";
            if (type == typeof(UnsignedLongField)) return "UnsignedLongField";
            if (type == typeof(EnumField)) return "EnumField";
            if (type == typeof(DropdownField)) return "DropdownField";
            if (type == typeof(ProgressBar)) return "ProgressBar";
            if (type == typeof(Foldout)) return "Foldout";
            if (type == typeof(Scroller)) return "Scroller";
            if (type == typeof(Tab)) return "Tab";
            if (type == typeof(TabView)) return "TabView";
            if (type == typeof(ListView)) return "ListView";
            if (type == typeof(TreeView)) return "TreeView";
            if (type == typeof(MultiColumnListView)) return "MultiColumnListView";
            if (type == typeof(MultiColumnTreeView)) return "MultiColumnTreeView";
            return "VisualElement";
        }
    }
}
